// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Animation                    string
	AnimationFrame               string
	AnimationFramePixel          string
	AnimationFramePropPosition   string
	AnimationFrameStaticPosition string
	BodyType                     string
	ColorString                  string
	DynamicPart                  string
	DynamicPartMapping           string
	DynamicPartMappingPixel      string
	DynamicPartPixel             string
	Prop                         string
	PropImage                    string
	SchemaMigrations             string
	StaticPart                   string
	StaticPartImage              string
}{
	Animation:                    "animation",
	AnimationFrame:               "animation_frame",
	AnimationFramePixel:          "animation_frame_pixel",
	AnimationFramePropPosition:   "animation_frame_prop_position",
	AnimationFrameStaticPosition: "animation_frame_static_position",
	BodyType:                     "body_type",
	ColorString:                  "color_string",
	DynamicPart:                  "dynamic_part",
	DynamicPartMapping:           "dynamic_part_mapping",
	DynamicPartMappingPixel:      "dynamic_part_mapping_pixel",
	DynamicPartPixel:             "dynamic_part_pixel",
	Prop:                         "prop",
	PropImage:                    "prop_image",
	SchemaMigrations:             "schema_migrations",
	StaticPart:                   "static_part",
	StaticPartImage:              "static_part_image",
}
