docker_build(
  'ghcr.io/lancewells/loot-loadout/frontend:latest-dev',
  '../',
  dockerfile='../dev.dockerfile'
)

k8s_yaml(
  kustomize('./overlays/dev')
)

k8s_resource(
  'frontend',
  port_forwards=['3001:3000']
)
