// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: characterimage/v1/characterimage.proto

package characterimage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImagesClient is the client API for Images service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImagesClient interface {
	AddBody(ctx context.Context, in *AddBodyRequest, opts ...grpc.CallOption) (*AddBodyResponse, error)
	ListBody(ctx context.Context, in *ListBodiesRequest, opts ...grpc.CallOption) (*ListBodiesResponse, error)
	AddDynamicMapping(ctx context.Context, in *AddDynamicMappingRequest, opts ...grpc.CallOption) (*AddDynamicMappingResponse, error)
	AddStatic(ctx context.Context, in *AddStaticRequest, opts ...grpc.CallOption) (*AddStaticResponse, error)
	ListStatic(ctx context.Context, in *ListStaticRequest, opts ...grpc.CallOption) (*ListStaticResponse, error)
	AddDynamic(ctx context.Context, in *AddDynamicRequest, opts ...grpc.CallOption) (*AddDynamicResponse, error)
	ListDynamic(ctx context.Context, in *ListDynamicRequest, opts ...grpc.CallOption) (*ListDynamicResponse, error)
	AddAnimation(ctx context.Context, in *AddAnimationRequest, opts ...grpc.CallOption) (*AddAnimationResponse, error)
	ListAnimation(ctx context.Context, in *ListAnimationRequest, opts ...grpc.CallOption) (*ListAnimationResponse, error)
	AddFrame(ctx context.Context, in *AddFrameRequest, opts ...grpc.CallOption) (*AddFrameResponse, error)
	AddProp(ctx context.Context, in *AddPropRequest, opts ...grpc.CallOption) (*AddPropResponse, error)
	ListProps(ctx context.Context, in *ListPropsRequest, opts ...grpc.CallOption) (*ListPropsResponse, error)
}

type imagesClient struct {
	cc grpc.ClientConnInterface
}

func NewImagesClient(cc grpc.ClientConnInterface) ImagesClient {
	return &imagesClient{cc}
}

func (c *imagesClient) AddBody(ctx context.Context, in *AddBodyRequest, opts ...grpc.CallOption) (*AddBodyResponse, error) {
	out := new(AddBodyResponse)
	err := c.cc.Invoke(ctx, "/lantspants.lootloadout.characterimage.Images/AddBody", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) ListBody(ctx context.Context, in *ListBodiesRequest, opts ...grpc.CallOption) (*ListBodiesResponse, error) {
	out := new(ListBodiesResponse)
	err := c.cc.Invoke(ctx, "/lantspants.lootloadout.characterimage.Images/ListBody", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) AddDynamicMapping(ctx context.Context, in *AddDynamicMappingRequest, opts ...grpc.CallOption) (*AddDynamicMappingResponse, error) {
	out := new(AddDynamicMappingResponse)
	err := c.cc.Invoke(ctx, "/lantspants.lootloadout.characterimage.Images/AddDynamicMapping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) AddStatic(ctx context.Context, in *AddStaticRequest, opts ...grpc.CallOption) (*AddStaticResponse, error) {
	out := new(AddStaticResponse)
	err := c.cc.Invoke(ctx, "/lantspants.lootloadout.characterimage.Images/AddStatic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) ListStatic(ctx context.Context, in *ListStaticRequest, opts ...grpc.CallOption) (*ListStaticResponse, error) {
	out := new(ListStaticResponse)
	err := c.cc.Invoke(ctx, "/lantspants.lootloadout.characterimage.Images/ListStatic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) AddDynamic(ctx context.Context, in *AddDynamicRequest, opts ...grpc.CallOption) (*AddDynamicResponse, error) {
	out := new(AddDynamicResponse)
	err := c.cc.Invoke(ctx, "/lantspants.lootloadout.characterimage.Images/AddDynamic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) ListDynamic(ctx context.Context, in *ListDynamicRequest, opts ...grpc.CallOption) (*ListDynamicResponse, error) {
	out := new(ListDynamicResponse)
	err := c.cc.Invoke(ctx, "/lantspants.lootloadout.characterimage.Images/ListDynamic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) AddAnimation(ctx context.Context, in *AddAnimationRequest, opts ...grpc.CallOption) (*AddAnimationResponse, error) {
	out := new(AddAnimationResponse)
	err := c.cc.Invoke(ctx, "/lantspants.lootloadout.characterimage.Images/AddAnimation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) ListAnimation(ctx context.Context, in *ListAnimationRequest, opts ...grpc.CallOption) (*ListAnimationResponse, error) {
	out := new(ListAnimationResponse)
	err := c.cc.Invoke(ctx, "/lantspants.lootloadout.characterimage.Images/ListAnimation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) AddFrame(ctx context.Context, in *AddFrameRequest, opts ...grpc.CallOption) (*AddFrameResponse, error) {
	out := new(AddFrameResponse)
	err := c.cc.Invoke(ctx, "/lantspants.lootloadout.characterimage.Images/AddFrame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) AddProp(ctx context.Context, in *AddPropRequest, opts ...grpc.CallOption) (*AddPropResponse, error) {
	out := new(AddPropResponse)
	err := c.cc.Invoke(ctx, "/lantspants.lootloadout.characterimage.Images/AddProp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) ListProps(ctx context.Context, in *ListPropsRequest, opts ...grpc.CallOption) (*ListPropsResponse, error) {
	out := new(ListPropsResponse)
	err := c.cc.Invoke(ctx, "/lantspants.lootloadout.characterimage.Images/ListProps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImagesServer is the server API for Images service.
// All implementations must embed UnimplementedImagesServer
// for forward compatibility
type ImagesServer interface {
	AddBody(context.Context, *AddBodyRequest) (*AddBodyResponse, error)
	ListBody(context.Context, *ListBodiesRequest) (*ListBodiesResponse, error)
	AddDynamicMapping(context.Context, *AddDynamicMappingRequest) (*AddDynamicMappingResponse, error)
	AddStatic(context.Context, *AddStaticRequest) (*AddStaticResponse, error)
	ListStatic(context.Context, *ListStaticRequest) (*ListStaticResponse, error)
	AddDynamic(context.Context, *AddDynamicRequest) (*AddDynamicResponse, error)
	ListDynamic(context.Context, *ListDynamicRequest) (*ListDynamicResponse, error)
	AddAnimation(context.Context, *AddAnimationRequest) (*AddAnimationResponse, error)
	ListAnimation(context.Context, *ListAnimationRequest) (*ListAnimationResponse, error)
	AddFrame(context.Context, *AddFrameRequest) (*AddFrameResponse, error)
	AddProp(context.Context, *AddPropRequest) (*AddPropResponse, error)
	ListProps(context.Context, *ListPropsRequest) (*ListPropsResponse, error)
	mustEmbedUnimplementedImagesServer()
}

// UnimplementedImagesServer must be embedded to have forward compatible implementations.
type UnimplementedImagesServer struct {
}

func (UnimplementedImagesServer) AddBody(context.Context, *AddBodyRequest) (*AddBodyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBody not implemented")
}
func (UnimplementedImagesServer) ListBody(context.Context, *ListBodiesRequest) (*ListBodiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBody not implemented")
}
func (UnimplementedImagesServer) AddDynamicMapping(context.Context, *AddDynamicMappingRequest) (*AddDynamicMappingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDynamicMapping not implemented")
}
func (UnimplementedImagesServer) AddStatic(context.Context, *AddStaticRequest) (*AddStaticResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddStatic not implemented")
}
func (UnimplementedImagesServer) ListStatic(context.Context, *ListStaticRequest) (*ListStaticResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStatic not implemented")
}
func (UnimplementedImagesServer) AddDynamic(context.Context, *AddDynamicRequest) (*AddDynamicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDynamic not implemented")
}
func (UnimplementedImagesServer) ListDynamic(context.Context, *ListDynamicRequest) (*ListDynamicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDynamic not implemented")
}
func (UnimplementedImagesServer) AddAnimation(context.Context, *AddAnimationRequest) (*AddAnimationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAnimation not implemented")
}
func (UnimplementedImagesServer) ListAnimation(context.Context, *ListAnimationRequest) (*ListAnimationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAnimation not implemented")
}
func (UnimplementedImagesServer) AddFrame(context.Context, *AddFrameRequest) (*AddFrameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFrame not implemented")
}
func (UnimplementedImagesServer) AddProp(context.Context, *AddPropRequest) (*AddPropResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProp not implemented")
}
func (UnimplementedImagesServer) ListProps(context.Context, *ListPropsRequest) (*ListPropsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProps not implemented")
}
func (UnimplementedImagesServer) mustEmbedUnimplementedImagesServer() {}

// UnsafeImagesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImagesServer will
// result in compilation errors.
type UnsafeImagesServer interface {
	mustEmbedUnimplementedImagesServer()
}

func RegisterImagesServer(s grpc.ServiceRegistrar, srv ImagesServer) {
	s.RegisterService(&Images_ServiceDesc, srv)
}

func _Images_AddBody_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBodyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).AddBody(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lantspants.lootloadout.characterimage.Images/AddBody",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).AddBody(ctx, req.(*AddBodyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_ListBody_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBodiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).ListBody(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lantspants.lootloadout.characterimage.Images/ListBody",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).ListBody(ctx, req.(*ListBodiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_AddDynamicMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDynamicMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).AddDynamicMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lantspants.lootloadout.characterimage.Images/AddDynamicMapping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).AddDynamicMapping(ctx, req.(*AddDynamicMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_AddStatic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddStaticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).AddStatic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lantspants.lootloadout.characterimage.Images/AddStatic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).AddStatic(ctx, req.(*AddStaticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_ListStatic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStaticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).ListStatic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lantspants.lootloadout.characterimage.Images/ListStatic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).ListStatic(ctx, req.(*ListStaticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_AddDynamic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDynamicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).AddDynamic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lantspants.lootloadout.characterimage.Images/AddDynamic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).AddDynamic(ctx, req.(*AddDynamicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_ListDynamic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDynamicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).ListDynamic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lantspants.lootloadout.characterimage.Images/ListDynamic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).ListDynamic(ctx, req.(*ListDynamicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_AddAnimation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAnimationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).AddAnimation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lantspants.lootloadout.characterimage.Images/AddAnimation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).AddAnimation(ctx, req.(*AddAnimationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_ListAnimation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAnimationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).ListAnimation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lantspants.lootloadout.characterimage.Images/ListAnimation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).ListAnimation(ctx, req.(*ListAnimationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_AddFrame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFrameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).AddFrame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lantspants.lootloadout.characterimage.Images/AddFrame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).AddFrame(ctx, req.(*AddFrameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_AddProp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPropRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).AddProp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lantspants.lootloadout.characterimage.Images/AddProp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).AddProp(ctx, req.(*AddPropRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_ListProps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPropsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).ListProps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lantspants.lootloadout.characterimage.Images/ListProps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).ListProps(ctx, req.(*ListPropsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Images_ServiceDesc is the grpc.ServiceDesc for Images service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Images_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lantspants.lootloadout.characterimage.Images",
	HandlerType: (*ImagesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBody",
			Handler:    _Images_AddBody_Handler,
		},
		{
			MethodName: "ListBody",
			Handler:    _Images_ListBody_Handler,
		},
		{
			MethodName: "AddDynamicMapping",
			Handler:    _Images_AddDynamicMapping_Handler,
		},
		{
			MethodName: "AddStatic",
			Handler:    _Images_AddStatic_Handler,
		},
		{
			MethodName: "ListStatic",
			Handler:    _Images_ListStatic_Handler,
		},
		{
			MethodName: "AddDynamic",
			Handler:    _Images_AddDynamic_Handler,
		},
		{
			MethodName: "ListDynamic",
			Handler:    _Images_ListDynamic_Handler,
		},
		{
			MethodName: "AddAnimation",
			Handler:    _Images_AddAnimation_Handler,
		},
		{
			MethodName: "ListAnimation",
			Handler:    _Images_ListAnimation_Handler,
		},
		{
			MethodName: "AddFrame",
			Handler:    _Images_AddFrame_Handler,
		},
		{
			MethodName: "AddProp",
			Handler:    _Images_AddProp_Handler,
		},
		{
			MethodName: "ListProps",
			Handler:    _Images_ListProps_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "characterimage/v1/characterimage.proto",
}
