apiVersion: v1
kind: Service
metadata:
  name: public-api-service
spec:
  ports:
  - name: http-port-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: grpc-port
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: public-api-deployment
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-api-deployment
  template:
    metadata:
      labels:
        app: public-api-deployment
    spec:
      containers:
      - image: ghcr.io/lancewells/loot-loadout/public-api:latest
        name: public-api
        ports:
        - containerPort: 8080
          name: http-port
        - containerPort: 9090
          name: grpc-port
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    dev.okteto.com/generate-host: "true"
  labels:
    name: public-api
  name: public-api
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: public-api-service
            port:
              number: 8080
        path: /
        pathType: Prefix
      - backend:
          service:
            name: public-api-service
            port:
              number: 9090
        path: /stream
        pathType: Prefix
