apiVersion: v1
kind: Service
metadata:
  name: room-socket
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: room-socket
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-socket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-socket
  template:
    metadata:
      labels:
        app: room-socket
    spec:
      containers:
      - image: ghcr.io/lancewells/loot-loadout/room-socket
        name: roomsocket
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
