apiVersion: apps/v1
kind: Deployment
metadata:
  name: character-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: character-image
  template:
    metadata:
      labels:
        app: character-image
    spec:
      containers:
      - name: character-image
        image: ghcr.io/lancewells/loot-loadout/character-image:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: POSTGRES_DB
            value: $CHARIMAGE_DB_DBNAME
          - name: POSTGRES_USER
            value: $CHARIMAGE_DB_USER
          - name: POSTGRES_PASSWORD
            value: $CHARIMAGE_DB_PASS
          - name: POSTGRES_PORT
            value: $CHARIMAGE_DB_PORT
      initContainers:
        - name: character-image-db-migrate
          image: ghcr.io/lancewells/loot-loadout/character-image-migration:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
          - name: POSTGRES_DB
            value: $CHARIMAGE_DB_DBNAME
          - name: POSTGRES_USER
            value: $CHARIMAGE_DB_USER
          - name: POSTGRES_PASSWORD
            value: $CHARIMAGE_DB_PASS
          - name: POSTGRES_PORT
            value: $CHARIMAGE_DB_PORT
