apiVersion: v1
kind: Service
metadata:
  name: public-api-service
spec:
  type: LoadBalancer
  selector:
    app: public-api-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
status:
  loadBalancer: {}
