apiVersion: v1
kind: Service
metadata:
  name: public-api-service
spec:
  type: LoadBalancer
  selector:
    app: public-api-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http-port-8080
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http-port-80
    - protocol: TCP
      port: 443
      targetPort: 9090
      name: grpc-port
status:
  loadBalancer: {}
