docker_build(
  'ghcr.io/lancewells/loot-loadout/room-socket:latest-dev',
  '../../../',
  dockerfile='../dev.dockerfile',
  only=[
    'api/',
    'backend/roomsocket/',
    'go.mod',
    'go.sum',
  ]
)

k8s_yaml(
  kustomize('./overlays/dev')
)

k8s_resource(
  'room-socket',
  port_forwards=['8002:8888', '40002:40000']
)
