docker_build(
  'lantspants/lootloadout/roomsocket:latest-dev',
  '../../../',
  dockerfile='../dev.dockerfile'
)

k8s_yaml(
  kustomize('./overlays/dev')
)

k8s_resource(
  'room-socket-deployment',
  port_forwards=['8002:8080', '40002:40000']
)
