apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-socket
spec:
  selector:
    replicas: 1
    matchLabels:
      app: room-socket
  template:
    metadata:
      labels:
        app: room-socket
    spec:
      containers:
      - name: roomsocket
        image: ghcr.io/lancewells/loot-loadout/room-socket:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
