docker_build(
  'ghcr.io/lancewells/loot-loadout/public-api:latest-dev',
  '../../../',
  dockerfile='../dev.dockerfile',
  only=[
    'api/',
    'backend/publicapi/',
    'go.mod',
    'go.sum',
  ]
)

k8s_yaml(
  kustomize('./overlays/dev')
)

k8s_resource(
  'public-api',
  port_forwards=['8001:8888', '40001:40000', '9001:9999']
)
