docker_build(
  'lantspants/lootloadout/public-api:latest-dev',
  '../../../',
  dockerfile='../dev.dockerfile'
)

k8s_yaml(
  kustomize('./overlays/dev')
)

k8s_resource(
  'public-api-deployment',
  port_forwards=['8001:8080', '40001:40000', '9001:9090']
)
