FROM golang:1.18.2 AS build

WORKDIR /app

COPY go.mod .
COPY go.sum .
COPY api api
COPY backend/roomsocket backend/roomsocket

EXPOSE 8888

RUN go build -o /app/app ./backend/roomsocket/cmd/
CMD ["/app/app"]
