FROM golang:1.18.2 AS build

WORKDIR /app

COPY go.mod .
COPY go.sum .
COPY api api
COPY backend/characterimage backend/characterimage

EXPOSE 8888 9999

RUN go build -o /app/app ./backend/characterimage/cmd/
CMD ["/app/app"]
