apiVersion: apps/v1
kind: Deployment
metadata:
  name: character-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: character-image
  template:
    metadata:
      labels:
        app: character-image
    spec:
      containers:
      - name: character-image
        image: ghcr.io/lancewells/loot-loadout/character-image:latest-dev
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: character-image-db
                key: dbname
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: character-image-db
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: character-image-db
                key: password
          - name: POSTGRES_PORT
            value: "5432"
      initContainers:
        - name: character-image-db-migrate
          image: ghcr.io/lancewells/loot-loadout/character-image-migration:latest-dev
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: character-image-db
                key: dbname
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: character-image-db
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: character-image-db
                key: password
          - name: POSTGRES_PORT
            value: "5432"
