apiVersion: v1
kind: Service
metadata:
  name: room-socket-service
spec:
  type: LoadBalancer
  selector:
    app: room-socket-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
status:
  loadBalancer: {}
